---
- name: Install terminal environment
  hosts: all
  gather_facts: no

  vars:
    packages:
      - go
      - hugo 

    go_directories:
      - ~/workspace/Go/src/github.com/mauriciovieira
      - ~/workspace/Go/bin
      - ~/workspace/Go/pkg

  tasks:
    - name: Ensure Go directories exist
      file: path="{{ item }}" state=directory
      with_items: "{{ go_directories }}"

    - name: Install Homebrew packages
      homebrew: name={{ packages }} state=latest
